services:
  - type: web
    name: expense-manager
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false # Will be set in Render dashboard
      - key: JWT_SECRET
        sync: false # Will be set in Render dashboard
    staticPublishPath: ./frontend/dist 